### ISSUE TITLE
Error: Could not find MIME for Buffer

### ISSUE THREAD

**Issue by uetchy** [takanakahiko/kotoba-palette#10]
ことばパレットに「ことばパレット」を入れると
```
エラーになりました : Error: Error: Could not find MIME for Buffer
```
というエラーが出ました。

Safari 13

**Comment by takanakahiko** [comment]
ありがとうございます！
画像検索の結果内に，存在しない画像が指定されていたり，画像形式が想定していないものであったりする場合があり，こうなるみたいです．

そのような場合に２枚めの画像を参照する等の仕組みを考えてみます．

**Comment by takanakahiko** [comment]
過去に修正していた( https://github.com/takanakahiko/kotoba-palette/commit/95e1f89162bbba97ca8da94847342b8a3ecf578d )のですがデプロイができていなかったのが原因でした．
デプロイし直しました．
ありがとうございました！
